.TH TM 1 2017-06-18
.SH NAME
tm \- a text-based stopwatch/countdown timer tool
.SH SYNOPSIS
.B tm
[\fIDURATION\fR]
.SH DESCRIPTION
.B tm
is a command line utility that is capable of creating stopwatch timers (which
start at zero and count up forever) and countdown timers (which start at a
given duration and count to zero, sending a notification when they finish).
.SH BUGS
The command line parser is extremely buggy and will choke on anything remotely
unrecognizable.
.SH AUTHOR
KeyboardFire <andy@keyboardfire.com>
